### ISSUE TITLE
Provide data for floorplan heatmap

### ISSUE THREAD

**Issue by henrym2** [henrym2/Sweng-11#15]
If we're going to display data on a heatmap we're going to need a sensible way to supply it

- [ ] Investigate how to associate locations with temperature data
- [ ] Modify data models to include locations with temperature data
- [ ] Ensure database can handle new data changes
- [ ] Provide fronted with location specific temperature data

Time estimate: 1 and a half weeks (give or take)

Related to #14

**Comment by MystikHub** [comment]
Duplicate issue
