### ISSUE TITLE
Design UI/UX for the basic MVP 

### ISSUE THREAD

**Issue by henrym2** [henrym2/Sweng-11#3]
Need to design the following pages

- [ ] Submission page
- [ ] Login/Registration page

Microsoft suggested we check out [Office UI Fabric](https://developer.microsoft.com/en-us/fabric#/)

Admittedly for the MVP those two pages could be made into one?

Probably should [MockFlow](https://mockflow.com/) for wireframing? Maybe overkill for the start

Time estimate : 1 or 2 days max

**Comment by AmMilu** [comment]
first design for both pages are in requirement documents.
