### ISSUE TITLE
Design expected sensor data schema

### ISSUE THREAD

**Issue by henrym2** [henrym2/Sweng-11#31]
The expected sensor data schema must be agreed on. At present I would expect it to look like the following. Please comment any other specification changes. I would imagine that once every minute or once every 5 minutes would suffice.

```json
{
    "id": "String",
    "location": "String",
    "temperature": "Float",
    "time": "timeStamp (String)"
}
```
Time estimate 1 day

**Comment by MystikHub** [comment]
How do we identify desks at the moment?

**Comment by henrym2** [comment]
If you look at the floorplan you'll be able to see each desk has both a
number and a letter. The letter is the area and the number is the desk

**Comment by MystikHub** [comment]
Ok, I finally found the floor plan. I was considering splitting the area and number from the location, but I don't see how that would help us right now. I think this specification is as good as any.
We can probably close this issue for now.

**Comment by henrym2** [comment]
Cool beans that sounds like a good plan for sure
