### ISSUE TITLE
Prevent users from voting too often

### ISSUE THREAD

**Issue by henrym2** [henrym2/Sweng-11#37]
When a user attempts to vote, the backend service will check and see if the user has voted before. 
If they have, the service will check to see if that vote was made in a recent timeframe (i.e 1 minute).
One of two things should happen after this check is made,
1. The time between current vote and last vote is > 1 minute, and the users vote is stored. A 200 response is sent along with an acknowledgement response to the fronted. `{ voted: true }`
2. The time between current vote and last vote is < 1 minute, the users vote is not stored. A _status 429 response is sent, along with a Retry-after header, this should be handled by an alert on the frontend_
Time estimate: 2 days

(Anything in italics is a change based on customer input)

**Comment by davidleacy** [comment]
You wouldn't return 200 in the failure case, you'd probably want to return 429 Too many requests and maybe add a Retry-after header.

**Comment by henrym2** [comment]
Thanks for the advice David, we'll change accordingly.
